build_tbb_dpl_spec:
  stage: build
  tags: [docker_linux]
  image: tr_ubuntu18.04:base
  script:
    - apt install -y python3 python3-pip
    - python3 -m pip install -r requirements.txt
    - python3 scripts/oneapi.py html source/elements/oneTBB
    - python3 scripts/oneapi.py html source/elements/oneDPL
  artifacts:
    paths: [source/elements/oneTBB/build/html, source/elements/oneDPL/build/html]
    expire_in: 3d

pages:
  stage: deploy
  tags: [linux]
  needs: [build_tbb_dpl_spec]
  only: [develop]
  script:
  - mkdir -p public
  - mv source/elements/oneTBB/build/html public/oneTBB
  - mv source/elements/oneDPL/build/html public/oneDPL
  artifacts:
    paths: [public]
